/*
 * generated by Xtext
 */
package st.redline;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmalltalkRuntimeModule extends st.redline.AbstractSmalltalkRuntimeModule {

}
