/*
* generated by Xtext
*/
package st.redline.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SmalltalkOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
