/*
 * generated by Xtext
 */
package st.redline.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SmalltalkUiModule extends st.redline.ui.AbstractSmalltalkUiModule {
	public SmalltalkUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
