/*
* generated by Xtext
*/
package st.redline.ui.contentassist;

import st.redline.ui.contentassist.AbstractSmalltalkProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SmalltalkProposalProvider extends AbstractSmalltalkProposalProvider {

}
